version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - godot
    - govet
    - ineffassign
    - lll
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    godot:
      scope: toplevel
    govet:
      enable:
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - errorsas
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - structtag
        - testinggoroutine
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
      enable-all: false
      disable-all: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 240
      tab-width: 4
    misspell:
      locale: US
    revive:
      confidence: 0.8
      severity: error
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: deep-exit
          disabled: true
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
          disabled: true
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: identical-branches
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: imports-blocklist
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: var-naming
        - name: var-declaration
        - name: unexported-return
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
