{{- $syncConfigRendered := tpl (required "syncConfig is not provided" .Values.syncConfig) . -}}
{{- $syncConfig := fromYaml $syncConfigRendered | default (dict) -}}
{{- if and (eq .Values.syncSource "ldap") .Values.ldap.caRootBundle -}}
{{- $ldapCfg := (index $syncConfig "ldap") | default (dict) -}}
{{- $ldapCAKey := required "ldap.caRootBundle.key is not provided" .Values.ldap.caRootBundle.key -}}
{{- $_ := set $ldapCfg "custom_root_ca" (printf "/etc/ytsaurus-identity-sync/%s" $ldapCAKey) -}}
{{- $_ := set $syncConfig "ldap" $ldapCfg -}}
{{- end -}}
{{- if and (eq .Values.syncSource "keycloak") .Values.keycloak.caRootBundle -}}
{{- $keycloakCfg := (index $syncConfig "keycloak") | default (dict) -}}
{{- $keycloakCAKey := required "keycloak.caRootBundle.key is not provided" .Values.keycloak.caRootBundle.key -}}
{{- $_ := set $keycloakCfg "custom_root_ca" (printf "/etc/ytsaurus-identity-sync/%s" $keycloakCAKey) -}}
{{- $_ := set $syncConfig "keycloak" $keycloakCfg -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ytsaurus-identity-sync.fullname" . }}
  labels:
    {{- include "ytsaurus-identity-sync.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml $syncConfig | nindent 4 }}
