apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ytsaurus-identity-sync.fullname" . }}
  labels:
    {{- include "ytsaurus-identity-sync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ytsaurus-identity-sync.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.plainSecrets.enabled }}
        checksum/plainSecret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.externalSecrets.enabled }}
        checksum/externalSecret: {{ include (print $.Template.BasePath "/externalsecret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.sealedSecrets.enabled }}
        checksum/sealedSecret: {{ include (print $.Template.BasePath "/sealedsecret.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ytsaurus-identity-sync.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ytsaurus-identity-sync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/ytsaurus-identity-sync", "--config", "/etc/ytsaurus-identity-sync/config.yaml" ]
          env:
            - name: YT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "ytsaurus-identity-sync.fullname" . | quote }}
                  key: YT_TOKEN
            {{- if eq .Values.syncSource "ldap" }}
            - name: LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ytsaurus-identity-sync.fullname" . | quote }}
                  key: LDAP_PASSWORD
            {{- else if eq .Values.syncSource "azure" }}
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ytsaurus-identity-sync.fullname" . | quote }}
                  key: AZURE_CLIENT_SECRET
            {{- else if eq .Values.syncSource "keycloak" }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ytsaurus-identity-sync.fullname" . | quote }}
                  key: KEYCLOAK_CLIENT_SECRET
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/ytsaurus-identity-sync
            {{- if and (eq .Values.syncSource "ldap") .Values.ldap.caRootBundle }}
            {{- if ne (required "ldap.caRootBundle.kind is not provided" .Values.ldap.caRootBundle.kind) "Secret" }}
            {{- fail "ldap.caRootBundle.kind must be Secret" }}
            {{- end }}
            {{- $ldapCAKey := required "ldap.caRootBundle.key is not provided" .Values.ldap.caRootBundle.key }}
            - name: ldap-ca-root-bundle
              mountPath: {{ printf "/etc/ytsaurus-identity-sync/%s" $ldapCAKey | quote }}
              subPath: {{ $ldapCAKey | quote }}
              readOnly: true
            {{- end }}
            {{- if and (eq .Values.syncSource "keycloak") .Values.keycloak.caRootBundle }}
            {{- if ne (required "keycloak.caRootBundle.kind is not provided" .Values.keycloak.caRootBundle.kind) "Secret" }}
            {{- fail "keycloak.caRootBundle.kind must be Secret" }}
            {{- end }}
            {{- $keycloakCAKey := required "keycloak.caRootBundle.key is not provided" .Values.keycloak.caRootBundle.key }}
            - name: keycloak-ca-root-bundle
              mountPath: {{ printf "/etc/ytsaurus-identity-sync/%s" $keycloakCAKey | quote }}
              subPath: {{ $keycloakCAKey | quote }}
              readOnly: true
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ytsaurus-identity-sync.fullname" . | quote }}
            items:
              - key: config.yaml
                path: config.yaml
        {{- if and (eq .Values.syncSource "ldap") .Values.ldap.caRootBundle }}
        {{- if ne (required "ldap.caRootBundle.kind is not provided" .Values.ldap.caRootBundle.kind) "Secret" }}
        {{- fail "ldap.caRootBundle.kind must be Secret" }}
        {{- end }}
        {{- $ldapCAKey := required "ldap.caRootBundle.key is not provided" .Values.ldap.caRootBundle.key }}
        - name: ldap-ca-root-bundle
          secret:
            secretName: {{ required "ldap.caRootBundle.name is not provided" .Values.ldap.caRootBundle.name | quote }}
            items:
              - key: {{ $ldapCAKey | quote }}
                path: {{ $ldapCAKey | quote }}
        {{- end }}
        {{- if and (eq .Values.syncSource "keycloak") .Values.keycloak.caRootBundle }}
        {{- if ne (required "keycloak.caRootBundle.kind is not provided" .Values.keycloak.caRootBundle.kind) "Secret" }}
        {{- fail "keycloak.caRootBundle.kind must be Secret" }}
        {{- end }}
        {{- $keycloakCAKey := required "keycloak.caRootBundle.key is not provided" .Values.keycloak.caRootBundle.key }}
        - name: keycloak-ca-root-bundle
          secret:
            secretName: {{ required "keycloak.caRootBundle.name is not provided" .Values.keycloak.caRootBundle.name | quote }}
            items:
              - key: {{ $keycloakCAKey | quote }}
                path: {{ $keycloakCAKey | quote }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
